### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by millner1998** [gabyfle/Lice#15]
Where did your addon gName-Changer go? Absolutely need it

**Comment by gabyfle** [comment]
Hi, the code is unmaintened, so I dropped support for it and made the repository private.

You can still get it from the Steam Workshop.

**Comment by millner1998** [comment]
> Hi, the code is unmaintened, so I dropped support for it and make the repository private.
> 
> You can still get it from the Steam Workshop.

Do you have a link for it?

**Comment by gabyfle** [comment]
> > Hi, the code is unmaintened, so I dropped support for it and make the repository private.
> > You can still get it from the Steam Workshop.
> 
> Do you have a link for it?

Mea culpa, it's not available anymore on the Steam Workshop for some obscure reasons. I made the repository available back as an archive.

Here is the link: https://github.com/gabyfle/gName-Changer
